### ISSUE TITLE
Landmark question

### ISSUE THREAD

**Issue by Riv67** [Riv67/web-design-2-independent-project#3]
Hi Jess @JessJodoin
I’m hoping you can help me with this markbot error:

![Screen Shot 2020-12-18 at 11 25 01 AM](https://user-images.githubusercontent.com/55094177/102637810-963adc00-4124-11eb-87cc-a4d10434d8fd.png)
All my other “role” attributes are working okay but I can’t figure this one out. (this is on line 56 of my index.html code)

**Comment by JessJodoin** [comment]
Oh, it's because your footer is in your `<main>` tag. If you move it out of the main so that it's inside the body, that should get rid of the error 😄
